const packages = [
  // Individual packages
  {
    name: "Single 6M",
    category: "individual",
    sport: "general",
    durationMonths: 6,
    price: 1750,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Single 1Y",
    category: "individual",
    sport: "general",
    durationMonths: 12,
    price: 3000,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Friends packages
  {
    name: "Friends 3M",
    category: "friends",
    sport: "general",
    durationMonths: 3,
    price: 1687.5,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Friends 6M",
    category: "friends",
    sport: "general",
    durationMonths: 6,
    price: 3099,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Friends 12M",
    category: "friends",
    sport: "general",
    durationMonths: 12,
    price: 4990,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Family essential packages
  {
    name: "Family Essential 3M",
    category: "family_essential",
    sport: "general",
    durationMonths: 3,
    price: 1312.5,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Family Essential 6M",
    category: "family_essential",
    sport: "general",
    durationMonths: 6,
    price: 2730,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Family Essential 1Y",
    category: "family_essential",
    sport: "general",
    durationMonths: 12,
    price: 4620,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Sub adult packages
  {
    name: "Sub Adult 3M",
    category: "sub_adult",
    sport: "general",
    durationMonths: 3,
    price: 699,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Sub Adult 6M",
    category: "sub_adult",
    sport: "general",
    durationMonths: 6,
    price: 1215,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Sub Adult 1Y",
    category: "sub_adult",
    sport: "general",
    durationMonths: 12,
    price: 1749,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Sub child monthly packages
  {
    name: "Sub Child Football Monthly",
    category: "sub_child",
    sport: "football",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 350,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Swimming Monthly",
    category: "sub_child",
    sport: "swimming",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 300,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Combat Monthly",
    category: "sub_child",
    sport: "combat",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Wrestling Monthly",
    category: "sub_child",
    sport: "wrestling",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child MMA Monthly",
    category: "sub_child",
    sport: "mma",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Jujitsu Monthly",
    category: "sub_child",
    sport: "jujitsu",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Judo Monthly",
    category: "sub_child",
    sport: "judo",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Boxing Monthly",
    category: "sub_child",
    sport: "boxing",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Kickboxing Monthly",
    category: "sub_child",
    sport: "kickboxing",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Taekwondo Monthly",
    category: "sub_child",
    sport: "taekwondo",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Karate Monthly",
    category: "sub_child",
    sport: "karate",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Gymnastics Monthly",
    category: "sub_child",
    sport: "gymnastics",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Ballet Monthly",
    category: "sub_child",
    sport: "ballet",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Fitness Monthly",
    category: "sub_child",
    sport: "fitness",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 230,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Football1 Monthly",
    category: "sub_child",
    sport: "football1",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 350,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Sub Child Football2 Monthly",
    category: "sub_child",
    sport: "football2",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 350,
    isFlexibleDuration: true,
    isActive: true,
  },

  // Academy only annual packages
  {
    name: "Academy Football Annual",
    category: "academy_only",
    sport: "football",
    durationMonths: 12,
    price: 4500,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Academy Swimming Annual",
    category: "academy_only",
    sport: "swimming",
    durationMonths: 12,
    price: 4000,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Academy Combat Annual",
    category: "academy_only",
    sport: "combat",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Academy only monthly packages (flexible)
  {
    name: "Academy Football Monthly",
    category: "academy_only",
    sport: "football",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 450,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Swimming Monthly",
    category: "academy_only",
    sport: "swimming",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 400,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Combat Monthly",
    category: "academy_only",
    sport: "combat",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy MMA Annual",
    category: "academy_only",
    sport: "mma",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Academy MMA Monthly",
    category: "academy_only",
    sport: "mma",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },

  // Wrestling packages
  {
    name: "Academy Wrestling Monthly",
    category: "academy_only",
    sport: "wrestling",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Wrestling Annual",
    category: "academy_only",
    sport: "wrestling",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Jujitsu packages
  {
    name: "Academy Jujitsu Monthly",
    category: "academy_only",
    sport: "jujitsu",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Jujitsu Annual",
    category: "academy_only",
    sport: "jujitsu",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Judo packages
  {
    name: "Academy Judo Monthly",
    category: "academy_only",
    sport: "judo",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Judo Annual",
    category: "academy_only",
    sport: "judo",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Boxing packages
  {
    name: "Academy Boxing Monthly",
    category: "academy_only",
    sport: "boxing",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Boxing Annual",
    category: "academy_only",
    sport: "boxing",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Football1 packages
  {
    name: "Academy Football1 Monthly",
    category: "academy_only",
    sport: "football1",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 450,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Football1 Annual",
    category: "academy_only",
    sport: "football1",
    durationMonths: 12,
    price: 4500,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Football2 packages
  {
    name: "Academy Football2 Monthly",
    category: "academy_only",
    sport: "football2",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 450,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Football2 Annual",
    category: "academy_only",
    sport: "football2",
    durationMonths: 12,
    price: 4500,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Ballet packages
  {
    name: "Academy Ballet Monthly",
    category: "academy_only",
    sport: "ballet",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 300,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Ballet Annual",
    category: "academy_only",
    sport: "ballet",
    durationMonths: 12,
    price: 3000,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Kickboxing packages
  {
    name: "Academy Kickboxing Monthly",
    category: "academy_only",
    sport: "kickboxing",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Kickboxing Annual",
    category: "academy_only",
    sport: "kickboxing",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Taekwondo packages
  {
    name: "Academy Taekwondo Monthly",
    category: "academy_only",
    sport: "taekwondo",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Taekwondo Annual",
    category: "academy_only",
    sport: "taekwondo",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Fitness packages
  {
    name: "Academy Fitness Monthly",
    category: "academy_only",
    sport: "fitness",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 300,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Fitness Annual",
    category: "academy_only",
    sport: "fitness",
    durationMonths: 12,
    price: 3000,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Karate packages
  {
    name: "Academy Karate Monthly",
    category: "academy_only",
    sport: "karate",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Karate Annual",
    category: "academy_only",
    sport: "karate",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Gymnastics packages
  {
    name: "Academy Gymnastics Monthly",
    category: "academy_only",
    sport: "gymnastics",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 300,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Gymnastics Annual",
    category: "academy_only",
    sport: "gymnastics",
    durationMonths: 12,
    price: 3000,
    isFlexibleDuration: false,
    isActive: true,
  },
];

module.exports = packages;
