const packages = [
  // Individual packages
  {
    name: "Single 6M",
    category: "individual",
    sport: "general",
    durationMonths: 6,
    price: 1750,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Single 1Y",
    category: "individual",
    sport: "general",
    durationMonths: 12,
    price: 3000,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Friends packages
  {
    name: "Friends 3M",
    category: "friends",
    sport: "general",
    durationMonths: 3,
    price: 1687.5,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Friends 6M",
    category: "friends",
    sport: "general",
    durationMonths: 6,
    price: 3099,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Friends 12M",
    category: "friends",
    sport: "general",
    durationMonths: 12,
    price: 4990,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Family essential packages
  {
    name: "Family Essential 3M",
    category: "family_essential",
    sport: "general",
    durationMonths: 3,
    price: 1312.5,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Family Essential 6M",
    category: "family_essential",
    sport: "general",
    durationMonths: 6,
    price: 2730,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Family Essential 1Y",
    category: "family_essential",
    sport: "general",
    durationMonths: 12,
    price: 4620,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Sub adult packages
  {
    name: "Sub Adult 3M",
    category: "sub_adult",
    sport: "general",
    durationMonths: 3,
    price: 699,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Sub Adult 6M",
    category: "sub_adult",
    sport: "general",
    durationMonths: 6,
    price: 1215,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Sub Adult 1Y",
    category: "sub_adult",
    sport: "general",
    durationMonths: 12,
    price: 1749,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Sub child monthly packages
  {
    name: "Sub Child Football Monthly",
    category: "sub_child",
    sport: "football",
    durationMonths: 1,
    price: 350,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Sub Child Swimming Monthly",
    category: "sub_child",
    sport: "swimming",
    durationMonths: 1,
    price: 300,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Sub Child Combat Monthly",
    category: "sub_child",
    sport: "combat",
    durationMonths: 1,
    price: 230,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Academy only annual packages
  {
    name: "Academy Football Annual",
    category: "academy_only",
    sport: "football",
    durationMonths: 12,
    price: 4500,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Academy Swimming Annual",
    category: "academy_only",
    sport: "swimming",
    durationMonths: 12,
    price: 4000,
    isFlexibleDuration: false,
    isActive: true,
  },
  {
    name: "Academy Combat Annual",
    category: "academy_only",
    sport: "combat",
    durationMonths: 12,
    price: 2300,
    isFlexibleDuration: false,
    isActive: true,
  },

  // Academy only monthly packages (flexible)
  {
    name: "Academy Football Monthly",
    category: "academy_only",
    sport: "football",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 450,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Swimming Monthly",
    category: "academy_only",
    sport: "swimming",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 400,
    isFlexibleDuration: true,
    isActive: true,
  },
  {
    name: "Academy Combat Monthly",
    category: "academy_only",
    sport: "combat",
    durationMonths: 1,
    price: 0,
    pricePerMonth: 330,
    isFlexibleDuration: true,
    isActive: true,
  },
];

module.exports = packages;
